### ISSUE TITLE
Assistants API needs updating

### ISSUE THREAD

**Issue by yozef** [boldare/openai-assistant#56]
Tool rename: The `retrieval` tool has been renamed to the `file_search` tool
Files belong to tools: Files are now associated with tools instead of Assistants and Messages. This means that:
AssistantFile and MessageFile objects no longer exist.
Instead of AssistantFile and MessageFile, files are attached to Assistants and Threads using the new tool_resources object.
The tool_resources for the code interpreter tool are a list of file_ids.
The tool_resources for the file_search tool are a new object called a vector_stores.
Messages now have an attachments, rather than a file_ids parameter. Message attachments are helpers that add the files to a Thread’s tool_resources.

https://platform.openai.com/docs/assistants/migration/what-has-changed

**Comment by sebastianmusial** [comment]
Hello @yozef ! Thank you for bringing this issue to our attention. We are going to address this matter in the upcoming days.
